version: "3.6"
services:
  file-server-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-server-api
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./uploadsv2:/app/uploadsv2
      - ./data:/app/data
    env_file:
      - .env
